---
  - name: Add nomad config
    template:
      src: config.hcl.j2
      dest: "{{config_dir}}/config-client.hcl"
    notify: Restart nomad
  
  - name: Install Packages
    ansible.builtin.package:
      name: "{{item}}"
    with_items:
      - podman

  - name: Create plugins Directory
    file:
      path: "{{item}}"
      state: directory
      owner: nomad
      group: nomad
    with_items: 
      - "{{data_dir}}/plugins"
      - /opt/cni/bin

# export ARCH_CNI=$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)
# export CNI_PLUGIN_VERSION=v1.6.2
# curl -L -o cni-plugins.tgz "https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGIN_VERSION}/cni-plugins-linux-${ARCH_CNI}-${CNI_PLUGIN_VERSION}".tgz && \
# sudo mkdir -p /opt/cni/bin && \
# sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz

  - name: download cni plugins
    get_url:
      url: "https://github.com/containernetworking/plugins/releases/download/{{CNI_PLUGIN_VERSION}}/cni-plugins-linux-amd64-{{CNI_PLUGIN_VERSION}}.tgz"
      dest: "/tmp/cni_{{CNI_PLUGIN_VERSION}}.tgz"
    when: ansible_architecture == "x86_64"

  - name: uzip cni plugin
    unarchive:
      src: "/tmp/cni_{{CNI_PLUGIN_VERSION}}.tgz"
      dest: /opt/cni/bin
      remote_src: true
    notify: Restart nomad

  - name: Install nomad-driver amd64
    ansible.builtin.get_url:
      url: https://releases.hashicorp.com/{{ item.name }}/{{ item.version }}/{{ item.name }}_{{ item.version }}_linux_amd64.zip
      dest: /tmp/{{ item.name }}-{{ item.version }}.zip
    when: ansible_architecture == "x86_64"
    with_items: 
      - name: nomad-driver-podman
        version: "0.6.1"
      - name: nomad-driver-exec2
        version: 0.1.0-beta.2
      - name: consul-cni
        version: "1.8.0"

  - name: Install nomad-driver arm64
    ansible.builtin.get_url:
      url: https://releases.hashicorp.com/{{ item.name }}/{{ item.version }}/{{ item.name }}_{{ item.version }}_linux_arm64.zip
      dest: /tmp/{{ item.name }}-{{ item.version }}.zip
    when: ansible_architecture == "aarch64"
    with_items: 
      - name: nomad-driver-podman
        version: "0.6.1"
      - name: nomad-driver-exec2
        version: 0.1.0-beta.2
      - name: consul-cni
        version: "1.8.0"
        
  - name: Unzip nomad-driver
    unarchive:
      src: /tmp/{{ item.name }}-{{ item.version }}.zip
      dest: "{{data_dir}}/plugins"
      remote_src: true
    notify: Restart nomad
    with_items: 
      - name: nomad-driver-podman
        version: "0.6.1"
      - name: nomad-driver-exec2
        version: 0.1.0-beta.2
      - name: consul-cni
        version: "1.8.0"