---
  - name: Add nomad config
    template:
      src: config.hcl.j2
      dest: "{{config_dir}}/config-client.hcl"
    notify: Restart nomad
  
  - name: Install Packages
    ansible.builtin.package:
      name: "{{item}}"
    with_items:
      - podman

  - name: Create plugins Directory
    file:
      path: "{{item}}"
      state: directory
      owner: nomad
      group: nomad
    with_items: 
      - "{{data_dir}}/plugins"

  - name: Install nomad-driver
    ansible.builtin.get_url:
      url: https://releases.hashicorp.com/{{ item.name }}/{{ item.version }}/{{ item.name }}_{{ item.version }}_linux_amd64.zip
      dest: /tmp{{ item.name }}-{{ item.version }}.zip
    with_items: 
      - name: nomad-driver-podman
        version: "0.6.1"
      - name: nomad-driver-exec2
        version: 0.1.0-beta.2
        
  - name: Unzip nomad-driver
    unarchive:
      src: /tmp{{ item.name }}-{{ item.version }}.zip
      dest: "{{data_dir}}/plugins"
      remote_src: true
    notify: Restart nomad
    with_items: 
      - name: nomad-driver-podman
        version: "0.6.1"
      - name: nomad-driver-exec2
        version: 0.1.0-beta.2