---
  - name: Add nomad config
    template:
      src: config.hcl.j2
      dest: "{{config_dir}}/config-client.hcl"
    notify: Restart nomad
  
  - name: Install Packages
    ansible.builtin.package:
      name: "{{item}}"
    with_items:
      - podman

  - name: Create plugins Directory
    file:
      path: "{{item}}"
      state: directory
      owner: nomad
      group: nomad
    with_items: 
      - "{{data_dir}}/plugins"

  - name: Install nomad-driver-podman
    ansible.builtin.get_url:
      url: https://releases.hashicorp.com/nomad-driver-podman/0.6.1/nomad-driver-podman_0.6.1_linux_amd64.zip
      dest: /tmp/nomad-driver-podman-0.6.1.zip
  
  - name: Unzip nomad-driver-podman
    unarchive:
      src: /tmp/nomad-driver-podman-0.6.1.zip
      dest: "{{data_dir}}/plugins"
      remote_src: true
    notify: Restart nomad