---

  - name: Install Packages
    ansible.builtin.package:
      name: "{{item}}"
    with_items:
      - unzip
      - jq
  
  - name: Create nomad Group
    group:
      name: "{{group}}"
  
  - name: Create nomad User
    user:
      name: "{{user}}"
      group: "{{group}}"
  
  - name: Install nomad amd64
    ansible.builtin.get_url:
      url: https://releases.hashicorp.com/nomad/{{ version }}/nomad_{{ version }}_linux_amd64.zip
      dest: /tmp/nomad{{ version }}.zip
    when: ansible_architecture == "x86_64"

  - name: Install nomad arm64
    ansible.builtin.get_url:
      url: https://releases.hashicorp.com/nomad/{{ version }}/nomad_{{ version }}_linux_arm64.zip
      dest: /tmp/nomad{{ version }}.zip
    when: ansible_architecture == "aarch64"
  
  - name: Unzip nomad
    unarchive:
      src: /tmp/nomad{{ version }}.zip
      dest: /usr/local/bin
      remote_src: true
    notify: Restart nomad
  
  - name: Wipe nomad Data
    file:
      path: "{{ data_dir }}"
      state: absent
    when: wipe_data
    notify: Restart nomad
  
  - name: Create nomad Directory
    file:
      path: "{{item}}"
      state: directory
      owner: nomad
      group: nomad
      mode: "0750"
    with_items: 
      - "{{ config_dir }}"
      - "{{ data_dir }}"
  
  
  - name: Add nomad config
    template:
      src: config.hcl.j2
      dest: "{{config_dir}}/config-base.hcl"
    notify: Restart nomad
  
  - name: Add nomad.Service
    template:
      src: nomad.service.j2
      dest: /etc/systemd/system/nomad.service
    notify: Restart nomad