---

- name: Create agent Directory
  file:
    path: "{{item}}"
    state: directory
    mode: "0750"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  with_items: 
  - "{{ config_dir }}/nomad"

- name: load template files
  template:
    src: "consul.tpl"
    dest: "{{ config_dir }}/nomad/consul.tpl"
    mode: "0440"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  notify:
    - Restart agent


- name: Load in agent config
  template:
    src: config.hcl.tpl
    dest: "{{ config_dir }}/nomad-config.hcl"
    mode: "0440"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  notify:
    - Restart agent

